version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis pour le cache
  redis:
    image: redis:6.0
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Service d'authentification
  authentication-service:
    build:
      context: ./server/authentication-service
      dockerfile: Dockerfile
    container_name: authentication-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SERVER_PORT: ${AUTHENTICATION_SERVICE_PORT}
    ports:
      - "${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  # Service de données communes
  common-data-service:
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    container_name: common-data-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_SCHEMA}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      ACTIVE_PROFILE: dev
      SERVER_PORT: ${COMMON_DATA_SERVICE_PORT}
    ports:
      - "${COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  # Service de paiement
  payment-service:
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
      SERVER_PORT: ${PAYMENT_SERVICE_PORT}
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    networks:
      - app-network

  # Frontend React
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    environment:
      - PORT=${REACT_APP_PORT}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}
      - REACT_APP_AUTH_API_URL=http://localhost:${AUTHENTICATION_SERVICE_PORT}
      - REACT_APP_COMMON_API_URL=http://localhost:${COMMON_DATA_SERVICE_PORT}
      - REACT_APP_PAYMENT_API_URL=http://localhost:${PAYMENT_SERVICE_PORT}
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    depends_on:
      - authentication-service
      - common-data-service
      - payment-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: